#:schema node_modules/wrangler/config-schema.json
name = "rin-server"
main = "server/src/_worker.ts"
compatibility_date = "2024-05-29"
# compatibility_flags = ["nodejs_compat"]
node_compat = true

[triggers]
crons = ["*/20 * * * *"]

[vars]
FRONTEND_URL = "http://localhost:5173"
S3_REGION = "auto"
S3_ENDPOINT = "<YourS3Endpoint>"
S3_FORCE_PATH_STYLE = "false"
IMG_BUCKET = "<YourImageBucket>"
IMG_FOLDER = "images/"
IMG_ACCESS_HOST = "<YourImageAccessHost>"
FILE_BUCKET = "<YourFileBucket>"
FILE_FOLDER = "files/"
FILE_ACCESS_HOST = "<YourFileAccessHost>"
CACHE_BUCKET = "<YourCacheBucket>"
CACHE_FOLDER = "cache/"
CACHE_ACCESS_HOST = "<YourCacheAccessHost>"
WEBHOOK_URL = "https://<YourWebhookURL>"
RSS_TITLE = "Rin Development Environment"
RSS_DESCRIPTION = "Development Environment"

[[d1_databases]]
binding = "DB"
database_name = "rin"
database_id = "YourDatabaseID"